### ISSUE TITLE
$string['mustdeleteextrarows'] 5 instead of 15 typo

### ISSUE THREAD

**Issue by lucaboesch** [ethz-let/qtype_mtf#1]
First of all, thanks for your excellent work!

In translating the strings to french, I think, I hit a typo.
In
https://github.com/ethz-let/qtype_mtf/blob/master/lang/en/qtype_mtf.php#L75 it states "Max allowed options in MTF are 5 options."
Now, I think, if I read
https://github.com/ethz-let/qtype_mtf/blob/master/edit_mtf_form.php#L144
correctly, the maximum allowed options are 15, not five.

No big deal, that message will only pop up if someone puts in more than 15 options, but the person will be puzzeled then.

Many greatings and kudos, again!

**Comment by isacsonk** [comment]
Hi Luca
Thanks a lot for reporting this typo, we will correct it as soon as we can.
Kristina

**Comment by nexterday** [comment]
Hi Luca. In the form you see 15 rows, which is the editor size (number or rows) and not the number of options for the question type. There is no mistake here.

**Comment by lucaboesch** [comment]
Oh, sorry Amr!
Please forget about this.
I was dazzeled by the phrasing "Max allowed options in MTF are 5 options."
Are there no 6 options or 7 options questions allowed?
(I probably should have tried it out…)

**Comment by lucaboesch** [comment]
It's perfectly possible to create a mtf question with 18 options.
I'm just wondering when the 15 set here https://github.com/ethz-let/qtype_mtf/blob/395dc24bee59829ee78d188c4a521375bda82db8/yui/form/form.js#L62 comes into place.

**Comment by nexterday** [comment]
Hi Luca. Yes and it was originally 15 options by default. We have another qtype which offers that and also single choice option. Mtf is derived from it. Its on github too, but we haven’t advertised it because we are busy with many other things.

**Comment by nexterday** [comment]
You can find it here: https://github.com/ethz-let/qtype_scmc

**Comment by isacsonk** [comment]
I should have tested too, before answering. ;-) I remembered earlier versions where we had discussed to have max options and thought it was a typo.
