### ISSUE TITLE
ERROR: Can not add jQuery plugins after starting page output!

### ISSUE THREAD

**Issue by germanvaleroelizondo** [ethz-let/qtype_mtf#10]
Hi,
I was making some demo screenshots for the documentation of this plugin at https://docs.moodle.org/36/en/Multiple_True/False_Question_Type and I found the following error:

Can not add jQuery plugins after starting page output!

    line 498 of \lib\outputrequirementslib.php: call to debugging()
    line 443 of \lib\outputrequirementslib.php: call to page_requirements_manager->jquery_plugin()
    line 99 of \question\type\mtf\renderer.php: call to page_requirements_manager->jquery()
    line 386 of \question\engine\renderer.php: call to qtype_mtf_renderer->formulation_and_controls()
    line 109 of \question\engine\renderer.php: call to core_question_renderer->formulation()
    line 113 of \question\behaviour\behaviourbase.php: call to core_question_renderer->question()
    line 841 of \question\engine\questionattempt.php: call to question_behaviour->render()
    line 449 of \question\engine\questionusage.php: call to question_attempt->render()
    line 253 of \question\preview.php: call to question_usage_by_activity->render_question()

Moodle 3.6.2+ (Build: 20190301)
MTF plugin 2.1 for Moodle 3.4+ 2019032200

**Comment by nexterday** [comment]
Hello. You seem to have the non latest version. Can you install the latest from master or from the release page: https://github.com/ethz-let/qtype_mtf/releases/tag/3.1

The version naming is 3.1

Let me know how it goes

**Comment by germanvaleroelizondo** [comment]
Hi,
I installed 1 hour ago from the Moodle plugins database.
I will delete and install newer version from here.

**Comment by germanvaleroelizondo** [comment]
I deleted the plugin directory and installed from ZIP from GitHub, and the errors disappeared :)

**Comment by nexterday** [comment]
Great.. I’ll close the issue and delete the old release on moodle just in case someone downloads earlier releases

**Comment by nexterday** [comment]
Great.. I’ll close the issue and delete the old release on moodle just in case someone downloads earlier releases

**Comment by germanvaleroelizondo** [comment]
BUT the file currently available in the Moodle plugins database which states 3.1 for Moodle 3.4+ (2019032200)Moodle 3.4, 3.5, 3.6

actually has release 2.1 inside version.php file :(

Can you please release a new plugin version with a new date for Moodle 3.4, 3.5 and 3.6 ?

**Comment by nexterday** [comment]
We changed versioning to match hence the confusion. I’ll fully remove the release and create new one, thanks for the note

**Comment by germanvaleroelizondo** [comment]
Thank you for another nice Moodle plugin :)
