### ISSUE TITLE
App display of the questions with dark mode

### ISSUE THREAD

**Issue by lucaboesch** [ethz-let/qtype_mtf#13]
The fact that the questions now display in the App is dope!
I noticed that when switched to dark mode, the text of the distractors wasn't visible any more.
Is that maybe because of the hard coded color codes in styles.css? Are those necessary at all?
Best,
Luca

**Comment by Clyxz** [comment]
Fixed -
Please refer: https://github.com/ethz-let/moodle-qtype_kprime/issues/27
