### ISSUE TITLE
With shuffleanswers = 1 mtfonezero evaluation is not accurately calculated every time

### ISSUE THREAD

**Issue by lucaboesch** [ethz-let/qtype_mtf#14]
Hi,
I unfortunately hit a bug.
If you take MTF 1/0 scoring method and you shuffle the options, the results are not calculated correctly. I'm here in front of a quiz attempt which shows 5 check marks of 5 correctly chosen options but the grade is 0.

To replicate (in PHPUnit):

Try to squeeze in
`$question->shuffleanswers = 1;`
as line 289 in question/type/mtf/tests/question_test.php and run the test_compute_final_grade_mtfonezero PHPUnit test several times.
It passes and fails randomly.

Best,
Luca

**Comment by Clyxz** [comment]
Hi Luca,
thank you for reporting this issue. I will take a look into it asap.

**Comment by nexterday** [comment]
Luca! what a brilliant catch, great to be seen by sharp naked eye. I suppose the behat test need to be adjusted (to shuffle order for real) to avoid false positives with shuffle, and for the actual bug, I suppose the option count (at the time of creating the question) is wrong, and a fix is on its way.

**Comment by Clyxz** [comment]
I made the same observations as Amr:
Numberofrows differs to the actual number of choices.

Numberofrows may be stored incorrectly if a user edits a MTF question and clicks on "blanks for 3 more choices" or deletes a choice. The number of rows will differ to the actual number of rows if some of the added choice remain empty with no optiontext entered by the teacher.

- Working on a fix for this

Hotfix for affected question:
1. Edit question
2. Save question
(3. Regrade test)

**Comment by Clyxz** [comment]
Hi Luca,
commit 50c344d fixes this issue and also should make the mechanics a bit more solid.
Please note:
This fix solves the issue but does not repair broken question.
For repairing the hotfix mentioned above can be applied.
